# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: XNIO CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-all:
    name: Compile (no tests) with JDK 8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: AdoptOpenJDK/install-jdk@v1
      name: Install JDK 8
      with:
        version: 8    
    - name: Build
      run: mvn -U -B -fae -DskipTests clean install
    - name: Tar Maven Repo
      shell: bash
      run: tar -czf maven-repo.tgz -C ~ .m2/repository
    - name: Persist Maven Repo
      uses: actions/upload-artifact@v1
      with:
        name: maven-repo
        path: maven-repo.tgz
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: surefire-reports-build
        path: '**/surefire-reports/*.txt'
  test-matrix:
    name: ${{ matrix.module }}-${{ matrix.openjdk_impl}}-${{ matrix.jdk }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build-all
    strategy:
      fail-fast: false
      matrix:
        module: [api, nio-impl]
        os: [ubuntu-20.04, windows-latest, macos-latest]
        jdk: [8, 11, 17, 21]
        openjdk_impl: [hotspot, openj9]
        exclude:
          - os: macos-latest
            openjdk_impl: openj9
          - os: windows-latest
            openjdk_impl: openj9
    steps:
    - name: Configure runner - Linux 
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo bash -c "echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4' > /etc/hosts"
        sudo bash -c "echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6' >> /etc/hosts"
        sudo apt-get update
        sudo apt-get install openssl net-tools -y
        sudo sysctl -w net.ipv4.ip_local_port_range="13000 64000"
        sudo sysctl -w net.ipv4.tcp_tw_reuse=0
    - name: Configure Runner - Windows
      if: contains(matrix.os, 'windows')
      run: |
        echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4' > %SystemRoot%\System32\drivers\etc\hosts
        echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6' >> %SystemRoot%\System32\drivers\etc\hosts
        choco install openssl --version=1.1.1.4 -y
        refreshenv
      shell: cmd
    - name: Configure Runner - OSX
      if: contains(matrix.os, 'macos')
      run: |
        brew update
        brew install openssl
        brew link --force openssl
        export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
        echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> /Users/runner/.bash_profile
        openssl version -a
        which openssl
    - name: Run netstat (pre)
      if: always()
      run: netstat -an
      shell: bash
    - uses: actions/checkout@v2
    - name: Download Maven Repo
      uses: actions/download-artifact@v1
      with:
        name: maven-repo
        path: .
    - name: Extract Maven Repo
      shell: bash
      run: tar -xzf maven-repo.tgz -C ~
    - name: Set up JDK ${{ matrix.java }}
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: ${{ matrix.jdk }}
        impl: ${{ matrix.jdk_impl }}
    - name: Run Tests
      run: mvn -U -B -fae test -pl ${{ matrix.module }}
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: surefire-reports-${{ matrix.module }}-${{ matrix.openjdk_impl}}-${{ matrix.jdk }}-${{ matrix.os }}
        path: '**/surefire-reports/*.txt'
    - name: Run netstat (post)
      if: always()
      run: netstat -an